version: '3'

services:
  space-flight-news:
    build: .
    ports:
      - "8080:80"
    volumes:
    - ./:/usr/share/nginx
    networks:
      - app-network
networks:
  app-network:
    driver: bridge